{
  "comment": "Relaxed rules",

  "default": true,
  "whitespace": false,
  "line-length": false,
  "ul-indent": false,
  "no-inline-html": false,
  "no-bare-urls": false,
  "fenced-code-language": false,
  "first-line-h1": false,
}
